# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseML-TextRecognition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/MLVision'
pod 'Firebase/MLVisionTextModel'

  target 'FirebaseML-TextRecognitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseML-TextRecognitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
